config/routes.rb
Rails.application.routes.draw do
  resources :inventory, only: [:new, :create, :index]
  get 'size/index'

  get 'apparel_type/index'

end

app/models/apparel_type.rb
class ApparelType < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :apparel_type
  belongs_to :size
end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/controllers/apparel_type_controller.rb
class ApparelTypeController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def new
    @apparels = ApparelType.all.map { |type| type.name }
    @sizes = Size.all.map { |size| size.variant }
  end

  def create

  end
end

app/controllers/size_controller.rb
class SizeController < ApplicationController
  def index
  end
end

app/helpers/apparel_type_helper.rb
module ApparelTypeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/size_helper.rb
module SizeHelper
end

app/views/apparel_type/index.html.erb
<h1>ApparelType#index</h1>
<p>Find me in app/views/apparel_type/index.html.erb</p>

app/views/inventory/create.html.erb
<h1>Inventory#create</h1>
<p>Find me in app/views/inventory/create.html.erb</p>

app/views/inventory/index.html.erb
<%  %>

app/views/inventory/new.html.erb
<div class="col-md-offset-4 col-md-4 text-center">
  <%= form_tag inventory_index_path, {id: 'inventory-form'} do %>

      <b class="pull-left"> Apparel Type: </b>
      <%= select_tag 'apparel_types',
                     options_for_select(@apparels),
                     include_blank: true,
                     class: 'form-control'
      %>
      <br>
      <b class="pull-left"> Size: </b>
      <%= select_tag 'sizes',
                     options_for_select(@sizes),
                     include_blank: true,
                     class: 'form-control'
      %>
      <br>
      <b class="pull-left"> Count: </b>
      <%= text_field_tag :quantity, nil %>
      <br>
      <%= button_tag 'Submit', class: "btn btn-default" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.js"></script>
  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <div class="jumbotron text-center">
    <h2> Siva Textiles </h2>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/size/index.html.erb
<h1>Size#index</h1>
<p>Find me in app/views/size/index.html.erb</p>